/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_zxseitz_jpl_math_Matrix4 */

#ifndef _Included_ch_zxseitz_jpl_math_Matrix4
#define _Included_ch_zxseitz_jpl_math_Matrix4
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_zxseitz_jpl_math_Matrix4_SIZE
#define ch_zxseitz_jpl_math_Matrix4_SIZE 16L
/*
 * Class:     ch_zxseitz_jpl_math_Matrix4
 * Method:    addC
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_zxseitz_jpl_math_Matrix4_addC
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_zxseitz_jpl_math_Matrix4
 * Method:    subtractC
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_zxseitz_jpl_math_Matrix4_subtractC
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_zxseitz_jpl_math_Matrix4
 * Method:    multiplyC
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_zxseitz_jpl_math_Matrix4_multiplyC
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_zxseitz_jpl_math_Matrix4
 * Method:    multiplyElementsC
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_zxseitz_jpl_math_Matrix4_multiplyElementsC
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_zxseitz_jpl_math_Matrix4
 * Method:    multiplyScalarC
 * Signature: ([FF[F)V
 */
JNIEXPORT void JNICALL Java_ch_zxseitz_jpl_math_Matrix4_multiplyScalarC
  (JNIEnv *, jclass, jfloatArray, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
